version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drafteam-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:3001
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    networks:
      - drafteam-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: drafteam-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/drafttracker.db
    env_file:
      - ./server/.env
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - database_data:/app/data
      - uploads_data:/app/uploads
    networks:
      - drafteam-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: drafteam-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - drafteam-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  database_data:
    driver: local
  uploads_data:
    driver: local

networks:
  drafteam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16